### ISSUE TITLE
Put phabricator.el on melpa

### ISSUE THREAD

**Issue by colonelpanic8** [ajtulloch/phabricator.el#1]
Any reason why this hasn't yet been done?

**Comment by yitang** [comment]
I think it's good idea to put it on melpa

**Comment by ajtulloch** [comment]
Sure, I'll do that if you'd like.

**Comment by ajtulloch** [comment]
Sorry for the delay, I missed this notification.

**Comment by yitang** [comment]
no problem, sounds like i got something to show off Monday

**Comment by ajtulloch** [comment]
Done, thanks!
